FROM debian:unstable

RUN apt-get update -y -qq

RUN apt-get install -y gcc g++ cmake clang liblmdb-dev

RUN apt-get install -y mesa-common-dev wget fuse git

RUN apt-get -y install ruby ruby-dev rubygems rpm && \
    gem install --no-ri --no-rdoc fpm

RUN apt-get update -qq && \
    apt-get install -y \
        qt5-default \
        qtbase5-dev \
        qttools5-dev-tools \
        qttools5-dev \
        qtmultimedia5-dev

RUN mkdir /build

WORKDIR /build
