[DEFAULTS]

[requests]
; Because currently (Qt 6.10) the official
; repository only has sha1 hashes, the default
; of sha256 fails when trying to download the checksums.
; E.g. https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt6_6103/qt6_6103/qt.qt6.6103.clang_64/
; if this changes this entire ini file can be removed or
; the hash_algorithm can be updated to sha256.
hash_algorithm: sha1
